In [10]:
import sys
import os
import numpy as np
from numpy import random
from PIL import Image
from collections import Counter

In [11]:
# prototype array
train_num = 100
train_img = np.zeros((10,train_num,28,28), dtype=np.float32)

In [12]:
# Input from user
args = sys.argv
# jupyter can't get input from stdin
#K = int(args[1])
K = 3

In [13]:
# Reading prototype from mnist data
for i in range(10):
  for j in range(1,train_num+1):
    train_file = "../data/mnist/train/" + str(i) + "/" + str(i) + "_" + str(j) + ".jpg"
    train_img[i][j-1] = np.asarray(Image.open(train_file).convert('L')).astype(np.float32)

In [14]:
# 混合行列
result = np.zeros((10,10), dtype=np.int32)

In [15]:
for i in range(10):
  for j in range(1,101):
    # 未知パターンの読み込み
    pat_file = "../data/mnist/test/" + str(i) + "/" + str(i) + "_" + str(j) + ".jpg"
    pat_img = np.asarray(Image.open(pat_file).convert('L')).astype(np.float32)

    min_val = np.full(K, np.inf)
    ans = np.zeros(K)
    # k-NN
    for k in range(10):
      for l in range(1,train_num+1):
        # Calculate SSD
        t = train_img[k][l-1].flatten()
        p = pat_img.flatten()
        dist = np.dot( (t-p).T , (t-p) )
        # explore minimum value
        for m in range(K):
          if dist < min_val[m]:
            min_val[m] = dist
            ans[m] = int(k)
            break
          else:
            continue
  c = Counter(ans)
  mode = c.most_common(1)
  count = np.array([v for key,v in sorted(c.items())])
  print(count)
  final_ans = int(mode[0][0])
  print(final_ans)
  # Output result
  result[i][final_ans] +=1
  print( i , j , "->" , ans, final_ans )
  
print( "\n [ 混合行列 ]" )
print( result )
print( "\n 正解数 -> " , np.trace(result) )


[1 2]
6
0 100 -> [0. 6. 6.] 6
[3]
1
1 100 -> [1. 1. 1.] 1
[3]
2
2 100 -> [2. 2. 2.] 2
[1 1 1]
1
3 100 -> [1. 5. 8.] 1
[3]
4
4 100 -> [4. 4. 4.] 4
[1 2]
9
5 100 -> [5. 9. 9.] 9
[3]
0
6 100 -> [0. 0. 0.] 0
[2 1]
7
7 100 -> [7. 9. 7.] 7
[3]
9
8 100 -> [9. 9. 9.] 9
[1 2]
5
9 100 -> [5. 0. 5.] 5

 [ 混合行列 ]
[[0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0]]

 正解数 ->  4
